### ISSUE TITLE
[QUESTION] Utilization Request

### ISSUE THREAD

**Issue by JosTheDude** [bashbunni/bashbunni.github.io#2]
Hey! I noticed you pop up on my youtube recommended and watched through one of your videos on NeoVim development, and decided to consider switching over to it myself. After I watched it, I checked out your GitHub and found this website a while ago. I recently bought a domain for a studio and parent company for my projects I was starting, and I was wondering if I could use the code (credit provided of course) for a Studio website I'm doing?

I couldn't find a contact email on your GitHub profile, so I decided to open a question here instead as there's no discussions tab either.

**Comment by ghost** [comment]
I used her code once and O BOY was it a nightmare. First off, she sued me, had my bank accounts frozen, put a tax lien on my properties, and Bash even went so far as to make a dis track where she made a rap video saying how much I suck because I copied her code. It was NOT fun to go through. 
That being said, any code posted publicly is expected to be shared. You read the license- it is WHERE you determine if code can be used. If there is NO license, its maybe a grey area but who posts code that they do not want shared and does not include the license terms? No one ever. That's who. The logic of license terms indicates that if there is NO license than it is open season, if there is a non-restrictive license than it is open season, if there is a restrictive license then most people are expected to abide by the terms of the license. That being said, famous websites like the USA White House have been busted lots of times for copying css/js from others and not giving credit as asked in the license terms. 
As always, consult your local, state , federal and global laws, then cross reference them with ICANN regulations, your internet service provider regulations and terms of service, and your operating system terms of service. Hope this helps clear things up.

**Comment by JosTheDude** [comment]
Thanks for the response! Yeah, I had figured since it had no license I could use it, but I still asked just to make sure ^^

Have an awesome day!
